# Phone codes seed data
PHONE_CODES = [
    {"country": "Afganistan", "country_code": "AF", "phone_code": "+93", "flag": "🇦🇫"},
    {"country": "Arnavutluk", "country_code": "AL", "phone_code": "+355", "flag": "🇦🇱"},
    {"country": "Cezayir", "country_code": "DZ", "phone_code": "+213", "flag": "🇩🇿"},
    {"country": "Amerikan Samoası", "country_code": "AS", "phone_code": "+1684", "flag": "🇦🇸"},
    {"country": "Andorra", "country_code": "AD", "phone_code": "+376", "flag": "🇦🇩"},
    {"country": "Angola", "country_code": "AO", "phone_code": "+244", "flag": "🇦🇴"},
    {"country": "Anguilla", "country_code": "AI", "phone_code": "+1264", "flag": "🇦🇮"},
    {"country": "Antarktika", "country_code": "AQ", "phone_code": "+672", "flag": "🇦🇶"},
    {"country": "Antigua ve Barbuda", "country_code": "AG", "phone_code": "+1268", "flag": "🇦🇬"},
    {"country": "Arjantin", "country_code": "AR", "phone_code": "+54", "flag": "🇦🇷"},
    {"country": "Ermenistan", "country_code": "AM", "phone_code": "+374", "flag": "🇦🇲"},
    {"country": "Aruba", "country_code": "AW", "phone_code": "+297", "flag": "🇦🇼"},
    {"country": "Avustralya", "country_code": "AU", "phone_code": "+61", "flag": "🇦🇺"},
    {"country": "Avusturya", "country_code": "AT", "phone_code": "+43", "flag": "🇦🇹"},
    {"country": "Azerbaycan", "country_code": "AZ", "phone_code": "+994", "flag": "🇦🇿"},
    {"country": "Bahamalar", "country_code": "BS", "phone_code": "+1242", "flag": "🇧🇸"},
    {"country": "Bahreyn", "country_code": "BH", "phone_code": "+973", "flag": "🇧🇭"},
    {"country": "Bangladeş", "country_code": "BD", "phone_code": "+880", "flag": "🇧🇩"},
    {"country": "Barbados", "country_code": "BB", "phone_code": "+1246", "flag": "🇧🇧"},
    {"country": "Belarus", "country_code": "BY", "phone_code": "+375", "flag": "🇧🇾"},
    {"country": "Belçika", "country_code": "BE", "phone_code": "+32", "flag": "🇧🇪"},
    {"country": "Belize", "country_code": "BZ", "phone_code": "+501", "flag": "🇧🇿"},
    {"country": "Benin", "country_code": "BJ", "phone_code": "+229", "flag": "🇧🇯"},
    {"country": "Bermuda", "country_code": "BM", "phone_code": "+1441", "flag": "🇧🇲"},
    {"country": "Butan", "country_code": "BT", "phone_code": "+975", "flag": "🇧🇹"},
    {"country": "Bolivya", "country_code": "BO", "phone_code": "+591", "flag": "🇧🇴"},
    {"country": "Bosna-Hersek", "country_code": "BA", "phone_code": "+387", "flag": "🇧🇦"},
    {"country": "Botsvana", "country_code": "BW", "phone_code": "+267", "flag": "🇧🇼"},
    {"country": "Brezilya", "country_code": "BR", "phone_code": "+55", "flag": "🇧🇷"},
    {"country": "Britanya Hint Okyanusu Bölgesi", "country_code": "IO", "phone_code": "+246", "flag": "🇮🇴"},
    {"country": "Brunei", "country_code": "BN", "phone_code": "+673", "flag": "🇧🇳"},
    {"country": "Bulgaristan", "country_code": "BG", "phone_code": "+359", "flag": "🇧🇬"},
    {"country": "Burkina Faso", "country_code": "BF", "phone_code": "+226", "flag": "🇧🇫"},
    {"country": "Burundi", "country_code": "BI", "phone_code": "+257", "flag": "🇧🇮"},
    {"country": "Kamboçya", "country_code": "KH", "phone_code": "+855", "flag": "🇰🇭"},
    {"country": "Kamerun", "country_code": "CM", "phone_code": "+237", "flag": "🇨🇲"},
    {"country": "Kanada", "country_code": "CA", "phone_code": "+1", "flag": "🇨🇦"},
    {"country": "Yeşil Burun Adaları", "country_code": "CV", "phone_code": "+238", "flag": "🇨🇻"},
    {"country": "Karayip Hollandası", "country_code": "BQ", "phone_code": "+599", "flag": "🇧🇶"},
    {"country": "Cayman Adaları", "country_code": "KY", "phone_code": "+1345", "flag": "🇰🇾"},
    {"country": "Orta Afrika Cumhuriyeti", "country_code": "CF", "phone_code": "+236", "flag": "🇨🇫"},
    {"country": "Çad", "country_code": "TD", "phone_code": "+235", "flag": "🇹🇩"},
    {"country": "Şili", "country_code": "CL", "phone_code": "+56", "flag": "🇨🇱"},
    {"country": "Çin", "country_code": "CN", "phone_code": "+86", "flag": "🇨🇳"},
    {"country": "Christmas Adası", "country_code": "CX", "phone_code": "+61", "flag": "🇨🇽"},
    {"country": "Cocos Adaları", "country_code": "CC", "phone_code": "+61", "flag": "🇨🇨"},
    {"country": "Kolombiya", "country_code": "CO", "phone_code": "+57", "flag": "🇨🇴"},
    {"country": "Komorlar", "country_code": "KM", "phone_code": "+269", "flag": "🇰🇲"},
    {"country": "Kongo Cumhuriyeti", "country_code": "CG", "phone_code": "+242", "flag": "🇨🇬"},
    {"country": "Kongo", "country_code": "CD", "phone_code": "+243", "flag": "🇨🇩"},
    {"country": "Cook Adaları", "country_code": "CK", "phone_code": "+682", "flag": "🇨🇰"},
    {"country": "Kosta Rika", "country_code": "CR", "phone_code": "+506", "flag": "🇨🇷"},
    {"country": "Hırvatistan", "country_code": "HR", "phone_code": "+385", "flag": "🇭🇷"},
    {"country": "Küba", "country_code": "CU", "phone_code": "+53", "flag": "🇨🇺"},
    {"country": "Curaçao", "country_code": "CW", "phone_code": "+599", "flag": "🇨🇼"},
    {"country": "Kıbrıs", "country_code": "CY", "phone_code": "+357", "flag": "🇨🇾"},
    {"country": "Çek Cumhuriyeti", "country_code": "CZ", "phone_code": "+420", "flag": "🇨🇿"},
    {"country": "Danimarka", "country_code": "DK", "phone_code": "+45", "flag": "🇩🇰"},
    {"country": "Cibuti", "country_code": "DJ", "phone_code": "+253", "flag": "🇩🇯"},
    {"country": "Dominika", "country_code": "DM", "phone_code": "+1767", "flag": "🇩🇲"},
    {"country": "Dominik Cumhuriyeti", "country_code": "DO", "phone_code": "+1809", "flag": "🇩🇴"},
    {"country": "Ekvador", "country_code": "EC", "phone_code": "+593", "flag": "🇪🇨"},
    {"country": "Mısır", "country_code": "EG", "phone_code": "+20", "flag": "🇪🇬"},
    {"country": "El Salvador", "country_code": "SV", "phone_code": "+503", "flag": "🇸🇻"},
    {"country": "Ekvator Ginesi", "country_code": "GQ", "phone_code": "+240", "flag": "🇬🇶"},
    {"country": "Eritre", "country_code": "ER", "phone_code": "+291", "flag": "🇪🇷"},
    {"country": "Estonya", "country_code": "EE", "phone_code": "+372", "flag": "🇪🇪"},
    {"country": "Esvatini", "country_code": "SZ", "phone_code": "+268", "flag": "🇸🇿"},
    {"country": "Etiyopya", "country_code": "ET", "phone_code": "+251", "flag": "🇪🇹"},
    {"country": "Falkland Adaları", "country_code": "FK", "phone_code": "+500", "flag": "🇫🇰"},
    {"country": "Faroe Adaları", "country_code": "FO", "phone_code": "+298", "flag": "🇫🇴"},
    {"country": "Fiji", "country_code": "FJ", "phone_code": "+679", "flag": "🇫🇯"},
    {"country": "Finlandiya", "country_code": "FI", "phone_code": "+358", "flag": "🇫🇮"},
    {"country": "Fransa", "country_code": "FR", "phone_code": "+33", "flag": "🇫🇷"},
    {"country": "Fransız Guyanası", "country_code": "GF", "phone_code": "+594", "flag": "🇬🇫"},
    {"country": "Fransız Polinezyası", "country_code": "PF", "phone_code": "+689", "flag": "🇵🇫"},
    {"country": "Gabon", "country_code": "GA", "phone_code": "+241", "flag": "🇬🇦"},
    {"country": "Gambiya", "country_code": "GM", "phone_code": "+220", "flag": "🇬🇲"},
    {"country": "Gürcistan", "country_code": "GE", "phone_code": "+995", "flag": "🇬🇪"},
    {"country": "Almanya", "country_code": "DE", "phone_code": "+49", "flag": "🇩🇪"},
    {"country": "Gana", "country_code": "GH", "phone_code": "+233", "flag": "🇬🇭"},
    {"country": "Cebelitarık", "country_code": "GI", "phone_code": "+350", "flag": "🇬🇮"},
    {"country": "Yunanistan", "country_code": "GR", "phone_code": "+30", "flag": "🇬🇷"},
    {"country": "Grönland", "country_code": "GL", "phone_code": "+299", "flag": "🇬🇱"},
    {"country": "Grenada", "country_code": "GD", "phone_code": "+1473", "flag": "🇬🇩"},
    {"country": "Guadeloupe", "country_code": "GP", "phone_code": "+590", "flag": "🇬🇵"},
    {"country": "Guam", "country_code": "GU", "phone_code": "+1671", "flag": "🇬🇺"},
    {"country": "Guatemala", "country_code": "GT", "phone_code": "+502", "flag": "🇬🇹"},
    {"country": "Guernsey", "country_code": "GG", "phone_code": "+44", "flag": "🇬🇬"},
    {"country": "Gine", "country_code": "GN", "phone_code": "+224", "flag": "🇬🇳"},
    {"country": "Gine-Bissau", "country_code": "GW", "phone_code": "+245", "flag": "🇬🇼"},
    {"country": "Guyana", "country_code": "GY", "phone_code": "+592", "flag": "🇬🇾"},
    {"country": "Haiti", "country_code": "HT", "phone_code": "+509", "flag": "🇭🇹"},
    {"country": "Heard ve McDonald Adaları", "country_code": "HM", "phone_code": "+672", "flag": "🇭🇲"},
    {"country": "Honduras", "country_code": "HN", "phone_code": "+504", "flag": "🇭🇳"},
    {"country": "Hong Kong", "country_code": "HK", "phone_code": "+852", "flag": "🇭🇰"},
    {"country": "Macaristan", "country_code": "HU", "phone_code": "+36", "flag": "🇭🇺"},
    {"country": "İzlanda", "country_code": "IS", "phone_code": "+354", "flag": "🇮🇸"},
    {"country": "Hindistan", "country_code": "IN", "phone_code": "+91", "flag": "🇮🇳"},
    {"country": "Endonezya", "country_code": "ID", "phone_code": "+62", "flag": "🇮🇩"},
    {"country": "İran", "country_code": "IR", "phone_code": "+98", "flag": "🇮🇷"},
    {"country": "Irak", "country_code": "IQ", "phone_code": "+964", "flag": "🇮🇶"},
    {"country": "İrlanda", "country_code": "IE", "phone_code": "+353", "flag": "🇮🇪"},
    {"country": "Man Adası", "country_code": "IM", "phone_code": "+44", "flag": "🇮🇲"},
    {"country": "İsrail", "country_code": "IL", "phone_code": "+972", "flag": "🇮🇱"},
    {"country": "İtalya", "country_code": "IT", "phone_code": "+39", "flag": "🇮🇹"},
    {"country": "Fildişi Sahili", "country_code": "CI", "phone_code": "+225", "flag": "🇨🇮"},
    {"country": "Jamaika", "country_code": "JM", "phone_code": "+1876", "flag": "🇯🇲"},
    {"country": "Japonya", "country_code": "JP", "phone_code": "+81", "flag": "🇯🇵"},
    {"country": "Jersey", "country_code": "JE", "phone_code": "+44", "flag": "🇯🇪"},
    {"country": "Ürdün", "country_code": "JO", "phone_code": "+962", "flag": "🇯🇴"},
    {"country": "Kazakistan", "country_code": "KZ", "phone_code": "+7", "flag": "🇰🇿"},
    {"country": "Kenya", "country_code": "KE", "phone_code": "+254", "flag": "🇰🇪"},
    {"country": "Kiribati", "country_code": "KI", "phone_code": "+686", "flag": "🇰🇮"},
    {"country": "Kosova", "country_code": "XK", "phone_code": "+383", "flag": "🇽🇰"},
    {"country": "Kuveyt", "country_code": "KW", "phone_code": "+965", "flag": "🇰🇼"},
    {"country": "Kırgızistan", "country_code": "KG", "phone_code": "+996", "flag": "🇰🇬"},
    {"country": "Laos", "country_code": "LA", "phone_code": "+856", "flag": "🇱🇦"},
    {"country": "Letonya", "country_code": "LV", "phone_code": "+371", "flag": "🇱🇻"},
    {"country": "Lübnan", "country_code": "LB", "phone_code": "+961", "flag": "🇱🇧"},
    {"country": "Lesotho", "country_code": "LS", "phone_code": "+266", "flag": "🇱🇸"},
    {"country": "Liberya", "country_code": "LR", "phone_code": "+231", "flag": "🇱🇷"},
    {"country": "Lihtenştayn", "country_code": "LI", "phone_code": "+423", "flag": "🇱🇮"},
    {"country": "Litvanya", "country_code": "LT", "phone_code": "+370", "flag": "🇱🇹"},
    {"country": "Lüksemburg", "country_code": "LU", "phone_code": "+352", "flag": "🇱🇺"},
    {"country": "Makao", "country_code": "MO", "phone_code": "+853", "flag": "🇲🇴"},
    {"country": "Kuzey Makedonya", "country_code": "MK", "phone_code": "+389", "flag": "🇲🇰"},
    {"country": "Madagaskar", "country_code": "MG", "phone_code": "+261", "flag": "🇲🇬"},
    {"country": "Malavi", "country_code": "MW", "phone_code": "+265", "flag": "🇲🇼"},
    {"country": "Malezya", "country_code": "MY", "phone_code": "+60", "flag": "🇲🇾"},
    {"country": "Maldivler", "country_code": "MV", "phone_code": "+960", "flag": "🇲🇻"},
    {"country": "Mali", "country_code": "ML", "phone_code": "+223", "flag": "🇲🇱"},
    {"country": "Malta", "country_code": "MT", "phone_code": "+356", "flag": "🇲🇹"},
    {"country": "Marshall Adaları", "country_code": "MH", "phone_code": "+692", "flag": "🇲🇭"},
    {"country": "Martinik", "country_code": "MQ", "phone_code": "+596", "flag": "🇲🇶"},
    {"country": "Moritanya", "country_code": "MR", "phone_code": "+222", "flag": "🇲🇷"},
    {"country": "Mauritius", "country_code": "MU", "phone_code": "+230", "flag": "🇲🇺"},
    {"country": "Mayotte", "country_code": "YT", "phone_code": "+262", "flag": "🇾🇹"},
    {"country": "Meksika", "country_code": "MX", "phone_code": "+52", "flag": "🇲🇽"},
    {"country": "Mikronezya", "country_code": "FM", "phone_code": "+691", "flag": "🇫🇲"},
    {"country": "Moldova", "country_code": "MD", "phone_code": "+373", "flag": "🇲🇩"},
    {"country": "Monako", "country_code": "MC", "phone_code": "+377", "flag": "🇲🇨"},
    {"country": "Moğolistan", "country_code": "MN", "phone_code": "+976", "flag": "🇲🇳"},
    {"country": "Karadağ", "country_code": "ME", "phone_code": "+382", "flag": "🇲🇪"},
    {"country": "Montserrat", "country_code": "MS", "phone_code": "+1664", "flag": "🇲🇸"},
    {"country": "Fas", "country_code": "MA", "phone_code": "+212", "flag": "🇲🇦"},
    {"country": "Mozambik", "country_code": "MZ", "phone_code": "+258", "flag": "🇲🇿"},
    {"country": "Myanmar", "country_code": "MM", "phone_code": "+95", "flag": "🇲🇲"},
    {"country": "Namibya", "country_code": "NA", "phone_code": "+264", "flag": "🇳🇦"},
    {"country": "Nauru", "country_code": "NR", "phone_code": "+674", "flag": "🇳🇷"},
    {"country": "Nepal", "country_code": "NP", "phone_code": "+977", "flag": "🇳🇵"},
    {"country": "Hollanda", "country_code": "NL", "phone_code": "+31", "flag": "🇳🇱"},
    {"country": "Yeni Kaledonya", "country_code": "NC", "phone_code": "+687", "flag": "🇳🇨"},
    {"country": "Yeni Zelanda", "country_code": "NZ", "phone_code": "+64", "flag": "🇳🇿"},
    {"country": "Nikaragua", "country_code": "NI", "phone_code": "+505", "flag": "🇳🇮"},
    {"country": "Nijer", "country_code": "NE", "phone_code": "+227", "flag": "🇳🇪"},
    {"country": "Nijerya", "country_code": "NG", "phone_code": "+234", "flag": "🇳🇬"},
    {"country": "Niue", "country_code": "NU", "phone_code": "+683", "flag": "🇳🇺"},
    {"country": "Norfolk Adası", "country_code": "NF", "phone_code": "+672", "flag": "🇳🇫"},
    {"country": "Kuzey Mariana Adaları", "country_code": "MP", "phone_code": "+1670", "flag": "🇲🇵"},
    {"country": "Kuzey Kore", "country_code": "KP", "phone_code": "+850", "flag": "🇰🇵"},
    {"country": "Norveç", "country_code": "NO", "phone_code": "+47", "flag": "🇳🇴"},
    {"country": "Umman", "country_code": "OM", "phone_code": "+968", "flag": "🇴🇲"},
    {"country": "Pakistan", "country_code": "PK", "phone_code": "+92", "flag": "🇵🇰"},
    {"country": "Palau", "country_code": "PW", "phone_code": "+680", "flag": "🇵🇼"},
    {"country": "Filistin", "country_code": "PS", "phone_code": "+970", "flag": "🇵🇸"},
    {"country": "Panama", "country_code": "PA", "phone_code": "+507", "flag": "🇵🇦"},
    {"country": "Papua Yeni Gine", "country_code": "PG", "phone_code": "+675", "flag": "🇵🇬"},
    {"country": "Paraguay", "country_code": "PY", "phone_code": "+595", "flag": "🇵🇾"},
    {"country": "Peru", "country_code": "PE", "phone_code": "+51", "flag": "🇵🇪"},
    {"country": "Filipinler", "country_code": "PH", "phone_code": "+63", "flag": "🇵🇭"},
    {"country": "Pitcairn", "country_code": "PN", "phone_code": "+872", "flag": "🇵🇳"},
    {"country": "Polonya", "country_code": "PL", "phone_code": "+48", "flag": "🇵🇱"},
    {"country": "Portekiz", "country_code": "PT", "phone_code": "+351", "flag": "🇵🇹"},
    {"country": "Porto Riko", "country_code": "PR", "phone_code": "+1", "flag": "🇵🇷"},
    {"country": "Katar", "country_code": "QA", "phone_code": "+974", "flag": "🇶🇦"},
    {"country": "Réunion", "country_code": "RE", "phone_code": "+262", "flag": "🇷🇪"},
    {"country": "Romanya", "country_code": "RO", "phone_code": "+40", "flag": "🇷🇴"},
    {"country": "Rusya", "country_code": "RU", "phone_code": "+7", "flag": "🇷🇺"},
    {"country": "Ruanda", "country_code": "RW", "phone_code": "+250", "flag": "🇷🇼"},
    {"country": "Sırbistan", "country_code": "RS", "phone_code": "+381", "flag": "🇷🇸"},
    {"country": "Seyşeller", "country_code": "SC", "phone_code": "+248", "flag": "🇸🇨"},
    {"country": "Sierra Leone", "country_code": "SL", "phone_code": "+232", "flag": "🇸🇱"},
    {"country": "Singapur", "country_code": "SG", "phone_code": "+65", "flag": "🇸🇬"},
    {"country": "Saint Helena", "country_code": "SH", "phone_code": "+290", "flag": "🇸🇭"},
    {"country": "Slovenya", "country_code": "SI", "phone_code": "+386", "flag": "🇸🇮"},
    {"country": "Solomon Adaları", "country_code": "SB", "phone_code": "+677", "flag": "🇸🇧"},
    {"country": "Somali", "country_code": "SO", "phone_code": "+252", "flag": "🇸🇴"},
    {"country": "Güney Afrika", "country_code": "ZA", "phone_code": "+27", "flag": "🇿🇦"},
    {"country": "Güney Georgia", "country_code": "GS", "phone_code": "+500", "flag": "🇬🇸"},
    {"country": "Güney Kore", "country_code": "KR", "phone_code": "+82", "flag": "🇰🇷"},
    {"country": "Güney Sudan", "country_code": "SS", "phone_code": "+211", "flag": "🇸🇸"},
    {"country": "İspanya", "country_code": "ES", "phone_code": "+34", "flag": "🇪🇸"},
    {"country": "Sri Lanka", "country_code": "LK", "phone_code": "+94", "flag": "🇱🇰"},
    {"country": "Sudan", "country_code": "SD", "phone_code": "+249", "flag": "🇸🇩"},
    {"country": "Surinam", "country_code": "SR", "phone_code": "+597", "flag": "🇸🇷"},
    {"country": "Svalbard", "country_code": "SJ", "phone_code": "+47", "flag": "🇸🇯"},
    {"country": "İsveç", "country_code": "SE", "phone_code": "+46", "flag": "🇸🇪"},
    {"country": "İsviçre", "country_code": "CH", "phone_code": "+41", "flag": "🇨🇭"},
    {"country": "Suriye", "country_code": "SY", "phone_code": "+963", "flag": "🇸🇾"},
    {"country": "Tayvan", "country_code": "TW", "phone_code": "+886", "flag": "🇹🇼"},
    {"country": "Tacikistan", "country_code": "TJ", "phone_code": "+992", "flag": "🇹🇯"},
    {"country": "Tanzanya", "country_code": "TZ", "phone_code": "+255", "flag": "🇹🇿"},
    {"country": "Tayland", "country_code": "TH", "phone_code": "+66", "flag": "🇹🇭"},
    {"country": "Doğu Timor", "country_code": "TL", "phone_code": "+670", "flag": "🇹🇱"},
    {"country": "Togo", "country_code": "TG", "phone_code": "+228", "flag": "🇹🇬"},
    {"country": "Tokelau", "country_code": "TK", "phone_code": "+690", "flag": "🇹🇰"},
    {"country": "Tonga", "country_code": "TO", "phone_code": "+676", "flag": "🇹🇴"},
    {"country": "Trinidad ve Tobago", "country_code": "TT", "phone_code": "+1868", "flag": "🇹🇹"},
    {"country": "Tunus", "country_code": "TN", "phone_code": "+216", "flag": "🇹🇳"},
    {"country": "Türkiye", "country_code": "TR", "phone_code": "+90", "flag": "🇹🇷"},
    {"country": "Tuvalu", "country_code": "TV", "phone_code": "+688", "flag": "🇹🇻"},
    {"country": "Uganda", "country_code": "UG", "phone_code": "+256", "flag": "🇺🇬"},
    {"country": "Ukrayna", "country_code": "UA", "phone_code": "+380", "flag": "🇺🇦"},
    {"country": "BAE", "country_code": "AE", "phone_code": "+971", "flag": "🇦🇪"},
    {"country": "Birleşik Krallık", "country_code": "GB", "phone_code": "+44", "flag": "🇬🇧"},
    {"country": "ABD", "country_code": "US", "phone_code": "+1", "flag": "🇺🇸"},
    {"country": "Uruguay", "country_code": "UY", "phone_code": "+598", "flag": "🇺🇾"},
    {"country": "Özbekistan", "country_code": "UZ", "phone_code": "+998", "flag": "🇺🇿"},
    {"country": "Vanuatu", "country_code": "VU", "phone_code": "+678", "flag": "🇻🇺"},
    {"country": "Vatikan", "country_code": "VA", "phone_code": "+379", "flag": "🇻🇦"},
    {"country": "Venezuela", "country_code": "VE", "phone_code": "+58", "flag": "🇻🇪"},
    {"country": "Vietnam", "country_code": "VN", "phone_code": "+84", "flag": "🇻🇳"},
    {"country": "Virgin Adaları (İngiliz)", "country_code": "VG", "phone_code": "+1284", "flag": "🇻🇬"},
    {"country": "Virgin Adaları (ABD)", "country_code": "VI", "phone_code": "+1340", "flag": "🇻🇮"},
    {"country": "Wallis ve Futuna", "country_code": "WF", "phone_code": "+681", "flag": "🇼🇫"},
    {"country": "Batı Sahra", "country_code": "EH", "phone_code": "+212", "flag": "🇪🇭"},
    {"country": "Yemen", "country_code": "YE", "phone_code": "+967", "flag": "🇾🇪"},
    {"country": "Zambiya", "country_code": "ZM", "phone_code": "+260", "flag": "🇿🇲"},
    {"country": "Zimbabve", "country_code": "ZW", "phone_code": "+263", "flag": "🇿🇼"},
]
