# Complete 195 UN Member Countries with major cities
# Generated automatically - DO NOT EDIT MANUALLY

COUNTRIES_195 = [
    {"id": "AF", "name": "Afganistan", "code": "AF"},
    {"id": "AL", "name": "Arnavutluk", "code": "AL"},
    {"id": "DZ", "name": "Cezayir", "code": "DZ"},
    {"id": "AD", "name": "Andorra", "code": "AD"},
    {"id": "AO", "name": "Angola", "code": "AO"},
    {"id": "AG", "name": "Antigua ve Barbuda", "code": "AG"},
    {"id": "AR", "name": "Arjantin", "code": "AR"},
    {"id": "AM", "name": "Ermenistan", "code": "AM"},
    {"id": "AU", "name": "Avustralya", "code": "AU"},
    {"id": "AT", "name": "Avusturya", "code": "AT"},
    {"id": "AZ", "name": "Azerbaycan", "code": "AZ"},
    {"id": "BS", "name": "Bahamalar", "code": "BS"},
    {"id": "BH", "name": "Bahreyn", "code": "BH"},
    {"id": "BD", "name": "Bangladeş", "code": "BD"},
    {"id": "BB", "name": "Barbados", "code": "BB"},
    {"id": "BY", "name": "Belarus", "code": "BY"},
    {"id": "BE", "name": "Belçika", "code": "BE"},
    {"id": "BZ", "name": "Belize", "code": "BZ"},
    {"id": "BJ", "name": "Benin", "code": "BJ"},
    {"id": "BT", "name": "Butan", "code": "BT"},
    {"id": "BO", "name": "Bolivya", "code": "BO"},
    {"id": "BA", "name": "Bosna-Hersek", "code": "BA"},
    {"id": "BW", "name": "Botsvana", "code": "BW"},
    {"id": "BR", "name": "Brezilya", "code": "BR"},
    {"id": "BN", "name": "Brunei", "code": "BN"},
    {"id": "BG", "name": "Bulgaristan", "code": "BG"},
    {"id": "BF", "name": "Burkina Faso", "code": "BF"},
    {"id": "BI", "name": "Burundi", "code": "BI"},
    {"id": "CV", "name": "Yeşil Burun Adaları", "code": "CV"},
    {"id": "KH", "name": "Kamboçya", "code": "KH"},
    {"id": "CM", "name": "Kamerun", "code": "CM"},
    {"id": "CA", "name": "Kanada", "code": "CA"},
    {"id": "CF", "name": "Orta Afrika Cumhuriyeti", "code": "CF"},
    {"id": "TD", "name": "Çad", "code": "TD"},
    {"id": "CL", "name": "Şili", "code": "CL"},
    {"id": "CN", "name": "Çin", "code": "CN"},
    {"id": "CO", "name": "Kolombiya", "code": "CO"},
    {"id": "KM", "name": "Komorlar", "code": "KM"},
    {"id": "CG", "name": "Kongo Cumhuriyeti", "code": "CG"},
    {"id": "CR", "name": "Kosta Rika", "code": "CR"},
    {"id": "HR", "name": "Hırvatistan", "code": "HR"},
    {"id": "CU", "name": "Küba", "code": "CU"},
    {"id": "CY", "name": "Kıbrıs", "code": "CY"},
    {"id": "CZ", "name": "Çek Cumhuriyeti", "code": "CZ"},
    {"id": "CD", "name": "Kongo Demokratik Cumhuriyeti", "code": "CD"},
    {"id": "DK", "name": "Danimarka", "code": "DK"},
    {"id": "DJ", "name": "Cibuti", "code": "DJ"},
    {"id": "DM", "name": "Dominika", "code": "DM"},
    {"id": "DO", "name": "Dominik Cumhuriyeti", "code": "DO"},
    {"id": "EC", "name": "Ekvador", "code": "EC"},
    {"id": "EG", "name": "Mısır", "code": "EG"},
    {"id": "SV", "name": "El Salvador", "code": "SV"},
    {"id": "GQ", "name": "Ekvator Ginesi", "code": "GQ"},
    {"id": "ER", "name": "Eritre", "code": "ER"},
    {"id": "EE", "name": "Estonya", "code": "EE"},
    {"id": "SZ", "name": "Esvatini", "code": "SZ"},
    {"id": "ET", "name": "Etiyopya", "code": "ET"},
    {"id": "FJ", "name": "Fiji", "code": "FJ"},
    {"id": "FI", "name": "Finlandiya", "code": "FI"},
    {"id": "FR", "name": "Fransa", "code": "FR"},
    {"id": "GA", "name": "Gabon", "code": "GA"},
    {"id": "GM", "name": "Gambiya", "code": "GM"},
    {"id": "GE", "name": "Gürcistan", "code": "GE"},
    {"id": "DE", "name": "Almanya", "code": "DE"},
    {"id": "GH", "name": "Gana", "code": "GH"},
    {"id": "GR", "name": "Yunanistan", "code": "GR"},
    {"id": "GD", "name": "Grenada", "code": "GD"},
    {"id": "GT", "name": "Guatemala", "code": "GT"},
    {"id": "GN", "name": "Gine", "code": "GN"},
    {"id": "GW", "name": "Gine-Bissau", "code": "GW"},
    {"id": "GY", "name": "Guyana", "code": "GY"},
    {"id": "HT", "name": "Haiti", "code": "HT"},
    {"id": "VA", "name": "Vatikan", "code": "VA"},
    {"id": "HN", "name": "Honduras", "code": "HN"},
    {"id": "HU", "name": "Macaristan", "code": "HU"},
    {"id": "IS", "name": "İzlanda", "code": "IS"},
    {"id": "IN", "name": "Hindistan", "code": "IN"},
    {"id": "ID", "name": "Endonezya", "code": "ID"},
    {"id": "IR", "name": "İran", "code": "IR"},
    {"id": "IQ", "name": "Irak", "code": "IQ"},
    {"id": "IE", "name": "İrlanda", "code": "IE"},
    {"id": "IL", "name": "İsrail", "code": "IL"},
    {"id": "IT", "name": "İtalya", "code": "IT"},
    {"id": "CI", "name": "Fildişi Sahili", "code": "CI"},
    {"id": "JM", "name": "Jamaika", "code": "JM"},
    {"id": "JP", "name": "Japonya", "code": "JP"},
    {"id": "JO", "name": "Ürdün", "code": "JO"},
    {"id": "KZ", "name": "Kazakistan", "code": "KZ"},
    {"id": "KE", "name": "Kenya", "code": "KE"},
    {"id": "KI", "name": "Kiribati", "code": "KI"},
    {"id": "KW", "name": "Kuveyt", "code": "KW"},
    {"id": "KG", "name": "Kırgızistan", "code": "KG"},
    {"id": "LA", "name": "Laos", "code": "LA"},
    {"id": "LV", "name": "Letonya", "code": "LV"},
    {"id": "LB", "name": "Lübnan", "code": "LB"},
    {"id": "LS", "name": "Lesotho", "code": "LS"},
    {"id": "LR", "name": "Liberya", "code": "LR"},
    {"id": "LY", "name": "Libya", "code": "LY"},
    {"id": "LI", "name": "Lihtenştayn", "code": "LI"},
    {"id": "LT", "name": "Litvanya", "code": "LT"},
    {"id": "LU", "name": "Lüksemburg", "code": "LU"},
    {"id": "MG", "name": "Madagaskar", "code": "MG"},
    {"id": "MW", "name": "Malavi", "code": "MW"},
    {"id": "MY", "name": "Malezya", "code": "MY"},
    {"id": "MV", "name": "Maldivler", "code": "MV"},
    {"id": "ML", "name": "Mali", "code": "ML"},
    {"id": "MT", "name": "Malta", "code": "MT"},
    {"id": "MH", "name": "Marshall Adaları", "code": "MH"},
    {"id": "MR", "name": "Moritanya", "code": "MR"},
    {"id": "MU", "name": "Mauritius", "code": "MU"},
    {"id": "MX", "name": "Meksika", "code": "MX"},
    {"id": "FM", "name": "Mikronezya", "code": "FM"},
    {"id": "MD", "name": "Moldova", "code": "MD"},
    {"id": "MC", "name": "Monako", "code": "MC"},
    {"id": "MN", "name": "Moğolistan", "code": "MN"},
    {"id": "ME", "name": "Karadağ", "code": "ME"},
    {"id": "MA", "name": "Fas", "code": "MA"},
    {"id": "MZ", "name": "Mozambik", "code": "MZ"},
    {"id": "MM", "name": "Myanmar", "code": "MM"},
    {"id": "NA", "name": "Namibya", "code": "NA"},
    {"id": "NR", "name": "Nauru", "code": "NR"},
    {"id": "NP", "name": "Nepal", "code": "NP"},
    {"id": "NL", "name": "Hollanda", "code": "NL"},
    {"id": "NZ", "name": "Yeni Zelanda", "code": "NZ"},
    {"id": "NI", "name": "Nikaragua", "code": "NI"},
    {"id": "NE", "name": "Nijer", "code": "NE"},
    {"id": "NG", "name": "Nijerya", "code": "NG"},
    {"id": "KP", "name": "Kuzey Kore", "code": "KP"},
    {"id": "MK", "name": "Kuzey Makedonya", "code": "MK"},
    {"id": "NO", "name": "Norveç", "code": "NO"},
    {"id": "OM", "name": "Umman", "code": "OM"},
    {"id": "PK", "name": "Pakistan", "code": "PK"},
    {"id": "PW", "name": "Palau", "code": "PW"},
    {"id": "PS", "name": "Filistin", "code": "PS"},
    {"id": "PA", "name": "Panama", "code": "PA"},
    {"id": "PG", "name": "Papua Yeni Gine", "code": "PG"},
    {"id": "PY", "name": "Paraguay", "code": "PY"},
    {"id": "PE", "name": "Peru", "code": "PE"},
    {"id": "PH", "name": "Filipinler", "code": "PH"},
    {"id": "PL", "name": "Polonya", "code": "PL"},
    {"id": "PT", "name": "Portekiz", "code": "PT"},
    {"id": "QA", "name": "Katar", "code": "QA"},
    {"id": "RO", "name": "Romanya", "code": "RO"},
    {"id": "RU", "name": "Rusya", "code": "RU"},
    {"id": "RW", "name": "Ruanda", "code": "RW"},
    {"id": "KN", "name": "Saint Kitts ve Nevis", "code": "KN"},
    {"id": "LC", "name": "Saint Lucia", "code": "LC"},
    {"id": "VC", "name": "Saint Vincent ve Grenadinler", "code": "VC"},
    {"id": "WS", "name": "Samoa", "code": "WS"},
    {"id": "SM", "name": "San Marino", "code": "SM"},
    {"id": "ST", "name": "São Tomé ve Príncipe", "code": "ST"},
    {"id": "SA", "name": "Suudi Arabistan", "code": "SA"},
    {"id": "SN", "name": "Senegal", "code": "SN"},
    {"id": "RS", "name": "Sırbistan", "code": "RS"},
    {"id": "SC", "name": "Seyşeller", "code": "SC"},
    {"id": "SL", "name": "Sierra Leone", "code": "SL"},
    {"id": "SG", "name": "Singapur", "code": "SG"},
    {"id": "SK", "name": "Slovakya", "code": "SK"},
    {"id": "SI", "name": "Slovenya", "code": "SI"},
    {"id": "SB", "name": "Solomon Adaları", "code": "SB"},
    {"id": "SO", "name": "Somali", "code": "SO"},
    {"id": "ZA", "name": "Güney Afrika", "code": "ZA"},
    {"id": "KR", "name": "Güney Kore", "code": "KR"},
    {"id": "SS", "name": "Güney Sudan", "code": "SS"},
    {"id": "ES", "name": "İspanya", "code": "ES"},
    {"id": "LK", "name": "Sri Lanka", "code": "LK"},
    {"id": "SD", "name": "Sudan", "code": "SD"},
    {"id": "SR", "name": "Surinam", "code": "SR"},
    {"id": "SE", "name": "İsveç", "code": "SE"},
    {"id": "CH", "name": "İsviçre", "code": "CH"},
    {"id": "SY", "name": "Suriye", "code": "SY"},
    {"id": "TJ", "name": "Tacikistan", "code": "TJ"},
    {"id": "TZ", "name": "Tanzanya", "code": "TZ"},
    {"id": "TH", "name": "Tayland", "code": "TH"},
    {"id": "TL", "name": "Doğu Timor", "code": "TL"},
    {"id": "TG", "name": "Togo", "code": "TG"},
    {"id": "TO", "name": "Tonga", "code": "TO"},
    {"id": "TT", "name": "Trinidad ve Tobago", "code": "TT"},
    {"id": "TN", "name": "Tunus", "code": "TN"},
    {"id": "TR", "name": "Türkiye", "code": "TR"},
    {"id": "TM", "name": "Türkmenistan", "code": "TM"},
    {"id": "TV", "name": "Tuvalu", "code": "TV"},
    {"id": "UG", "name": "Uganda", "code": "UG"},
    {"id": "UA", "name": "Ukrayna", "code": "UA"},
    {"id": "AE", "name": "Birleşik Arap Emirlikleri", "code": "AE"},
    {"id": "GB", "name": "Birleşik Krallık", "code": "GB"},
    {"id": "US", "name": "Amerika Birleşik Devletleri", "code": "US"},
    {"id": "UY", "name": "Uruguay", "code": "UY"},
    {"id": "UZ", "name": "Özbekistan", "code": "UZ"},
    {"id": "VU", "name": "Vanuatu", "code": "VU"},
    {"id": "VE", "name": "Venezuela", "code": "VE"},
    {"id": "VN", "name": "Vietnam", "code": "VN"},
    {"id": "YE", "name": "Yemen", "code": "YE"},
    {"id": "ZM", "name": "Zambiya", "code": "ZM"},
    {"id": "ZW", "name": "Zimbabve", "code": "ZW"},
]

ALL_CITIES = [
    # Türkiye (TR) - 20 major cities
    {"id": "TR-1", "name": "İstanbul", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-2", "name": "Ankara", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-3", "name": "İzmir", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-4", "name": "Bursa", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-5", "name": "Adana", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-6", "name": "Antalya", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-7", "name": "Gaziantep", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-8", "name": "Konya", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-9", "name": "Kayseri", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-10", "name": "Mersin", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-11", "name": "Diyarbakır", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-12", "name": "Eskişehir", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-13", "name": "Şanlıurfa", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-14", "name": "Malatya", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-15", "name": "Kahramanmaraş", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-16", "name": "Erzurum", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-17", "name": "Van", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-18", "name": "Denizli", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-19", "name": "Samsun", "country": "Türkiye", "countryCode": "TR"},
    {"id": "TR-20", "name": "Balıkesir", "country": "Türkiye", "countryCode": "TR"},

    # Amerika Birleşik Devletleri (US) - 20 major cities
    {"id": "US-21", "name": "New York", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-22", "name": "Los Angeles", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-23", "name": "Chicago", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-24", "name": "Houston", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-25", "name": "Phoenix", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-26", "name": "Philadelphia", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-27", "name": "San Antonio", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-28", "name": "San Diego", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-29", "name": "Dallas", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-30", "name": "San Jose", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-31", "name": "Austin", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-32", "name": "Jacksonville", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-33", "name": "Fort Worth", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-34", "name": "Columbus", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-35", "name": "Charlotte", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-36", "name": "San Francisco", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-37", "name": "Indianapolis", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-38", "name": "Seattle", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-39", "name": "Denver", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},
    {"id": "US-40", "name": "Boston", "country": "Amerika Birleşik Devletleri", "countryCode": "US"},

    # Birleşik Krallık (GB) - 20 major cities
    {"id": "GB-41", "name": "Londra", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-42", "name": "Birmingham", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-43", "name": "Manchester", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-44", "name": "Liverpool", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-45", "name": "Leeds", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-46", "name": "Newcastle", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-47", "name": "Sheffield", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-48", "name": "Bristol", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-49", "name": "Edinburgh", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-50", "name": "Glasgow", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-51", "name": "Leicester", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-52", "name": "Nottingham", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-53", "name": "Cardiff", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-54", "name": "Belfast", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-55", "name": "Southampton", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-56", "name": "Bradford", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-57", "name": "Plymouth", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-58", "name": "Derby", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-59", "name": "Portsmouth", "country": "Birleşik Krallık", "countryCode": "GB"},
    {"id": "GB-60", "name": "Stoke-on-Trent", "country": "Birleşik Krallık", "countryCode": "GB"},

    # Almanya (DE) - 20 major cities
    {"id": "DE-61", "name": "Berlin", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-62", "name": "Hamburg", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-63", "name": "Münih", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-64", "name": "Köln", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-65", "name": "Frankfurt", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-66", "name": "Stuttgart", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-67", "name": "Düsseldorf", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-68", "name": "Dortmund", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-69", "name": "Essen", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-70", "name": "Leipzig", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-71", "name": "Bremen", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-72", "name": "Dresden", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-73", "name": "Hannover", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-74", "name": "Nürnberg", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-75", "name": "Duisburg", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-76", "name": "Bochum", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-77", "name": "Wuppertal", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-78", "name": "Bielefeld", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-79", "name": "Bonn", "country": "Almanya", "countryCode": "DE"},
    {"id": "DE-80", "name": "Münster", "country": "Almanya", "countryCode": "DE"},

    # Fransa (FR) - 20 major cities
    {"id": "FR-81", "name": "Paris", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-82", "name": "Marsilya", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-83", "name": "Lyon", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-84", "name": "Toulouse", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-85", "name": "Nice", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-86", "name": "Nantes", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-87", "name": "Montpellier", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-88", "name": "Strasbourg", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-89", "name": "Bordeaux", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-90", "name": "Lille", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-91", "name": "Rennes", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-92", "name": "Reims", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-93", "name": "Toulon", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-94", "name": "Saint-Étienne", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-95", "name": "Le Havre", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-96", "name": "Grenoble", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-97", "name": "Dijon", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-98", "name": "Angers", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-99", "name": "Nîmes", "country": "Fransa", "countryCode": "FR"},
    {"id": "FR-100", "name": "Villeurbanne", "country": "Fransa", "countryCode": "FR"},

    # İtalya (IT) - 20 major cities
    {"id": "IT-101", "name": "Roma", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-102", "name": "Milano", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-103", "name": "Napoli", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-104", "name": "Torino", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-105", "name": "Palermo", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-106", "name": "Cenova", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-107", "name": "Bologna", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-108", "name": "Floransa", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-109", "name": "Bari", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-110", "name": "Catania", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-111", "name": "Verona", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-112", "name": "Venedik", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-113", "name": "Messina", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-114", "name": "Padova", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-115", "name": "Trieste", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-116", "name": "Taranto", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-117", "name": "Brescia", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-118", "name": "Parma", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-119", "name": "Prato", "country": "İtalya", "countryCode": "IT"},
    {"id": "IT-120", "name": "Modena", "country": "İtalya", "countryCode": "IT"},

    # İspanya (ES) - 20 major cities
    {"id": "ES-121", "name": "Madrid", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-122", "name": "Barselona", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-123", "name": "Valencia", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-124", "name": "Sevilla", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-125", "name": "Zaragoza", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-126", "name": "Malaga", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-127", "name": "Murcia", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-128", "name": "Palma", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-129", "name": "Las Palmas", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-130", "name": "Bilbao", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-131", "name": "Alicante", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-132", "name": "Córdoba", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-133", "name": "Valladolid", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-134", "name": "Vigo", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-135", "name": "Gijón", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-136", "name": "L'Hospitalet", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-137", "name": "Granada", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-138", "name": "Vitoria", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-139", "name": "Elche", "country": "İspanya", "countryCode": "ES"},
    {"id": "ES-140", "name": "Oviedo", "country": "İspanya", "countryCode": "ES"},

    # Çin (CN) - 20 major cities
    {"id": "CN-141", "name": "Şangay", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-142", "name": "Pekin", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-143", "name": "Guangzhou", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-144", "name": "Shenzhen", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-145", "name": "Chengdu", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-146", "name": "Tianjin", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-147", "name": "Chongqing", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-148", "name": "Wuhan", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-149", "name": "Hangzhou", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-150", "name": "Nanjing", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-151", "name": "Xi'an", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-152", "name": "Shenyang", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-153", "name": "Harbin", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-154", "name": "Qingdao", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-155", "name": "Jinan", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-156", "name": "Dalian", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-157", "name": "Zhengzhou", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-158", "name": "Kunming", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-159", "name": "Changsha", "country": "Çin", "countryCode": "CN"},
    {"id": "CN-160", "name": "Taiyuan", "country": "Çin", "countryCode": "CN"},

    # Japonya (JP) - 20 major cities
    {"id": "JP-161", "name": "Tokyo", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-162", "name": "Yokohama", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-163", "name": "Osaka", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-164", "name": "Nagoya", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-165", "name": "Sapporo", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-166", "name": "Fukuoka", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-167", "name": "Kobe", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-168", "name": "Kyoto", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-169", "name": "Kawasaki", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-170", "name": "Saitama", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-171", "name": "Hiroshima", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-172", "name": "Sendai", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-173", "name": "Chiba", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-174", "name": "Kitakyushu", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-175", "name": "Sakai", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-176", "name": "Niigata", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-177", "name": "Hamamatsu", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-178", "name": "Kumamoto", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-179", "name": "Sagamihara", "country": "Japonya", "countryCode": "JP"},
    {"id": "JP-180", "name": "Shizuoka", "country": "Japonya", "countryCode": "JP"},

    # Hindistan (IN) - 20 major cities
    {"id": "IN-181", "name": "Mumbai", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-182", "name": "Delhi", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-183", "name": "Bangalore", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-184", "name": "Haydarabad", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-185", "name": "Ahmedabad", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-186", "name": "Chennai", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-187", "name": "Kolkata", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-188", "name": "Pune", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-189", "name": "Jaipur", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-190", "name": "Surat", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-191", "name": "Lucknow", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-192", "name": "Kanpur", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-193", "name": "Nagpur", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-194", "name": "Indore", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-195", "name": "Thane", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-196", "name": "Bhopal", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-197", "name": "Visakhapatnam", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-198", "name": "Pimpri-Chinchwad", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-199", "name": "Patna", "country": "Hindistan", "countryCode": "IN"},
    {"id": "IN-200", "name": "Vadodara", "country": "Hindistan", "countryCode": "IN"},

    # Brezilya (BR) - 20 major cities
    {"id": "BR-201", "name": "São Paulo", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-202", "name": "Rio de Janeiro", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-203", "name": "Brasília", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-204", "name": "Salvador", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-205", "name": "Fortaleza", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-206", "name": "Belo Horizonte", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-207", "name": "Manaus", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-208", "name": "Curitiba", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-209", "name": "Recife", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-210", "name": "Porto Alegre", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-211", "name": "Belém", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-212", "name": "Goiânia", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-213", "name": "Guarulhos", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-214", "name": "Campinas", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-215", "name": "São Luís", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-216", "name": "São Gonçalo", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-217", "name": "Maceió", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-218", "name": "Duque de Caxias", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-219", "name": "Natal", "country": "Brezilya", "countryCode": "BR"},
    {"id": "BR-220", "name": "Campo Grande", "country": "Brezilya", "countryCode": "BR"},

    # Rusya (RU) - 20 major cities
    {"id": "RU-221", "name": "Moskova", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-222", "name": "Sankt Petersburg", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-223", "name": "Novosibirsk", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-224", "name": "Yekaterinburg", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-225", "name": "Kazan", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-226", "name": "Nizhny Novgorod", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-227", "name": "Chelyabinsk", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-228", "name": "Samara", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-229", "name": "Omsk", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-230", "name": "Rostov-on-Don", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-231", "name": "Ufa", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-232", "name": "Krasnoyarsk", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-233", "name": "Voronezh", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-234", "name": "Perm", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-235", "name": "Volgograd", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-236", "name": "Krasnodar", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-237", "name": "Saratov", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-238", "name": "Tyumen", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-239", "name": "Tolyatti", "country": "Rusya", "countryCode": "RU"},
    {"id": "RU-240", "name": "Izhevsk", "country": "Rusya", "countryCode": "RU"},

    # Kanada (CA) - 20 major cities
    {"id": "CA-241", "name": "Toronto", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-242", "name": "Montreal", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-243", "name": "Vancouver", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-244", "name": "Calgary", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-245", "name": "Edmonton", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-246", "name": "Ottawa", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-247", "name": "Winnipeg", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-248", "name": "Quebec City", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-249", "name": "Hamilton", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-250", "name": "Kitchener", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-251", "name": "London", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-252", "name": "Victoria", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-253", "name": "Halifax", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-254", "name": "Oshawa", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-255", "name": "Windsor", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-256", "name": "Saskatoon", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-257", "name": "Regina", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-258", "name": "Sherbrooke", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-259", "name": "St. John's", "country": "Kanada", "countryCode": "CA"},
    {"id": "CA-260", "name": "Barrie", "country": "Kanada", "countryCode": "CA"},

    # Avustralya (AU) - 20 major cities
    {"id": "AU-261", "name": "Sidney", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-262", "name": "Melbourne", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-263", "name": "Brisbane", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-264", "name": "Perth", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-265", "name": "Adelaide", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-266", "name": "Gold Coast", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-267", "name": "Newcastle", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-268", "name": "Canberra", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-269", "name": "Sunshine Coast", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-270", "name": "Wollongong", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-271", "name": "Hobart", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-272", "name": "Geelong", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-273", "name": "Townsville", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-274", "name": "Cairns", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-275", "name": "Darwin", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-276", "name": "Toowoomba", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-277", "name": "Ballarat", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-278", "name": "Bendigo", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-279", "name": "Albury", "country": "Avustralya", "countryCode": "AU"},
    {"id": "AU-280", "name": "Launceston", "country": "Avustralya", "countryCode": "AU"},

    # Meksika (MX) - 20 major cities
    {"id": "MX-281", "name": "Mexico City", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-282", "name": "Guadalajara", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-283", "name": "Monterrey", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-284", "name": "Puebla", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-285", "name": "Tijuana", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-286", "name": "León", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-287", "name": "Juárez", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-288", "name": "Zapopan", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-289", "name": "Mérida", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-290", "name": "San Luis Potosí", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-291", "name": "Aguascalientes", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-292", "name": "Hermosillo", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-293", "name": "Saltillo", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-294", "name": "Mexicali", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-295", "name": "Culiacán", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-296", "name": "Querétaro", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-297", "name": "Chihuahua", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-298", "name": "Morelia", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-299", "name": "Toluca", "country": "Meksika", "countryCode": "MX"},
    {"id": "MX-300", "name": "Cancún", "country": "Meksika", "countryCode": "MX"},

    # Güney Kore (KR) - 20 major cities
    {"id": "KR-301", "name": "Seul", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-302", "name": "Busan", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-303", "name": "Incheon", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-304", "name": "Daegu", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-305", "name": "Daejeon", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-306", "name": "Gwangju", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-307", "name": "Suwon", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-308", "name": "Ulsan", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-309", "name": "Goyang", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-310", "name": "Yongin", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-311", "name": "Seongnam", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-312", "name": "Changwon", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-313", "name": "Bucheon", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-314", "name": "Cheongju", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-315", "name": "Ansan", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-316", "name": "Jeonju", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-317", "name": "Anyang", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-318", "name": "Pohang", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-319", "name": "Cheonan", "country": "Güney Kore", "countryCode": "KR"},
    {"id": "KR-320", "name": "Namyangju", "country": "Güney Kore", "countryCode": "KR"},

    # Endonezya (ID) - 20 major cities
    {"id": "ID-321", "name": "Jakarta", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-322", "name": "Surabaya", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-323", "name": "Bandung", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-324", "name": "Bekasi", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-325", "name": "Medan", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-326", "name": "Depok", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-327", "name": "Tangerang", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-328", "name": "Palembang", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-329", "name": "Semarang", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-330", "name": "Makassar", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-331", "name": "South Tangerang", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-332", "name": "Batam", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-333", "name": "Bogor", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-334", "name": "Pekanbaru", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-335", "name": "Bandar Lampung", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-336", "name": "Padang", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-337", "name": "Malang", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-338", "name": "Denpasar", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-339", "name": "Surakarta", "country": "Endonezya", "countryCode": "ID"},
    {"id": "ID-340", "name": "Balikpapan", "country": "Endonezya", "countryCode": "ID"},

    # Hollanda (NL) - 20 major cities
    {"id": "NL-341", "name": "Amsterdam", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-342", "name": "Rotterdam", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-343", "name": "The Hague", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-344", "name": "Utrecht", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-345", "name": "Eindhoven", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-346", "name": "Groningen", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-347", "name": "Tilburg", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-348", "name": "Almere", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-349", "name": "Breda", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-350", "name": "Nijmegen", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-351", "name": "Enschede", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-352", "name": "Haarlem", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-353", "name": "Arnhem", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-354", "name": "Zaanstad", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-355", "name": "Amersfoort", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-356", "name": "Apeldoorn", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-357", "name": "s-Hertogenbosch", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-358", "name": "Hoofddorp", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-359", "name": "Maastricht", "country": "Hollanda", "countryCode": "NL"},
    {"id": "NL-360", "name": "Leiden", "country": "Hollanda", "countryCode": "NL"},

    # Suudi Arabistan (SA) - 20 major cities
    {"id": "SA-361", "name": "Riyad", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-362", "name": "Cidde", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-363", "name": "Mekke", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-364", "name": "Medine", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-365", "name": "Dammam", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-366", "name": "Taif", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-367", "name": "Buraidah", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-368", "name": "Tabük", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-369", "name": "Khamis Mushayt", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-370", "name": "Hofuf", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-371", "name": "Haradh", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-372", "name": "Khobar", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-373", "name": "Jubail", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-374", "name": "Hafar Al-Batin", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-375", "name": "Yanbu", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-376", "name": "Abha", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-377", "name": "Najran", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-378", "name": "Arar", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-379", "name": "Sakaka", "country": "Suudi Arabistan", "countryCode": "SA"},
    {"id": "SA-380", "name": "Jizan", "country": "Suudi Arabistan", "countryCode": "SA"},

    # İsviçre (CH) - 20 major cities
    {"id": "CH-381", "name": "Zürih", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-382", "name": "Cenevre", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-383", "name": "Basel", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-384", "name": "Bern", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-385", "name": "Lozan", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-386", "name": "Winterthur", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-387", "name": "Lucerne", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-388", "name": "St. Gallen", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-389", "name": "Lugano", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-390", "name": "Biel", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-391", "name": "Thun", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-392", "name": "Köniz", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-393", "name": "La Chaux-de-Fonds", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-394", "name": "Schaffhausen", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-395", "name": "Fribourg", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-396", "name": "Vernier", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-397", "name": "Chur", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-398", "name": "Neuchâtel", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-399", "name": "Uster", "country": "İsviçre", "countryCode": "CH"},
    {"id": "CH-400", "name": "Sion", "country": "İsviçre", "countryCode": "CH"},

    # Polonya (PL) - 20 major cities
    {"id": "PL-401", "name": "Varşova", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-402", "name": "Kraków", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-403", "name": "Łódź", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-404", "name": "Wrocław", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-405", "name": "Poznań", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-406", "name": "Gdańsk", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-407", "name": "Szczecin", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-408", "name": "Bydgoszcz", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-409", "name": "Lublin", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-410", "name": "Katowice", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-411", "name": "Białystok", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-412", "name": "Gdynia", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-413", "name": "Częstochowa", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-414", "name": "Radom", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-415", "name": "Sosnowiec", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-416", "name": "Toruń", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-417", "name": "Kielce", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-418", "name": "Gliwice", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-419", "name": "Zabrze", "country": "Polonya", "countryCode": "PL"},
    {"id": "PL-420", "name": "Bytom", "country": "Polonya", "countryCode": "PL"},

    # Belçika (BE) - 20 major cities
    {"id": "BE-421", "name": "Brüksel", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-422", "name": "Antwerp", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-423", "name": "Gent", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-424", "name": "Charleroi", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-425", "name": "Liège", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-426", "name": "Bruges", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-427", "name": "Namur", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-428", "name": "Leuven", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-429", "name": "Mons", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-430", "name": "Aalst", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-431", "name": "Mechelen", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-432", "name": "La Louvière", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-433", "name": "Kortrijk", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-434", "name": "Hasselt", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-435", "name": "Oostende", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-436", "name": "Genk", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-437", "name": "Sint-Niklaas", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-438", "name": "Tournai", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-439", "name": "Seraing", "country": "Belçika", "countryCode": "BE"},
    {"id": "BE-440", "name": "Roeselare", "country": "Belçika", "countryCode": "BE"},

    # Avusturya (AT) - 20 major cities
    {"id": "AT-441", "name": "Viyana", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-442", "name": "Graz", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-443", "name": "Linz", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-444", "name": "Salzburg", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-445", "name": "Innsbruck", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-446", "name": "Klagenfurt", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-447", "name": "Villach", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-448", "name": "Wels", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-449", "name": "Sankt Pölten", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-450", "name": "Dornbirn", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-451", "name": "Wiener Neustadt", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-452", "name": "Steyr", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-453", "name": "Feldkirch", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-454", "name": "Bregenz", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-455", "name": "Leonding", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-456", "name": "Klosterneuburg", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-457", "name": "Baden", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-458", "name": "Wolfsberg", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-459", "name": "Leoben", "country": "Avusturya", "countryCode": "AT"},
    {"id": "AT-460", "name": "Krems", "country": "Avusturya", "countryCode": "AT"},

    # İsveç (SE) - 20 major cities
    {"id": "SE-461", "name": "Stockholm", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-462", "name": "Göteborg", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-463", "name": "Malmö", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-464", "name": "Uppsala", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-465", "name": "Västerås", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-466", "name": "Örebro", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-467", "name": "Linköping", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-468", "name": "Helsingborg", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-469", "name": "Jönköping", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-470", "name": "Norrköping", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-471", "name": "Lund", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-472", "name": "Umeå", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-473", "name": "Gävle", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-474", "name": "Borås", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-475", "name": "Södertälje", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-476", "name": "Eskilstuna", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-477", "name": "Halmstad", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-478", "name": "Växjö", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-479", "name": "Karlstad", "country": "İsveç", "countryCode": "SE"},
    {"id": "SE-480", "name": "Sundsvall", "country": "İsveç", "countryCode": "SE"},

    # Norveç (NO) - 20 major cities
    {"id": "NO-481", "name": "Oslo", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-482", "name": "Bergen", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-483", "name": "Trondheim", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-484", "name": "Stavanger", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-485", "name": "Drammen", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-486", "name": "Fredrikstad", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-487", "name": "Kristiansand", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-488", "name": "Sandnes", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-489", "name": "Tromsø", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-490", "name": "Sarpsborg", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-491", "name": "Skien", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-492", "name": "Ålesund", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-493", "name": "Sandefjord", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-494", "name": "Haugesund", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-495", "name": "Tønsberg", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-496", "name": "Moss", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-497", "name": "Bodø", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-498", "name": "Arendal", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-499", "name": "Hamar", "country": "Norveç", "countryCode": "NO"},
    {"id": "NO-500", "name": "Larvik", "country": "Norveç", "countryCode": "NO"},

    # Danimarka (DK) - 20 major cities
    {"id": "DK-501", "name": "Kopenhag", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-502", "name": "Aarhus", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-503", "name": "Odense", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-504", "name": "Aalborg", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-505", "name": "Esbjerg", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-506", "name": "Randers", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-507", "name": "Kolding", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-508", "name": "Horsens", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-509", "name": "Vejle", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-510", "name": "Roskilde", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-511", "name": "Herning", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-512", "name": "Silkeborg", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-513", "name": "Næstved", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-514", "name": "Fredericia", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-515", "name": "Viborg", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-516", "name": "Køge", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-517", "name": "Holstebro", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-518", "name": "Taastrup", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-519", "name": "Slagelse", "country": "Danimarka", "countryCode": "DK"},
    {"id": "DK-520", "name": "Hillerød", "country": "Danimarka", "countryCode": "DK"},

    # Portekiz (PT) - 20 major cities
    {"id": "PT-521", "name": "Lizbon", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-522", "name": "Porto", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-523", "name": "Braga", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-524", "name": "Setúbal", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-525", "name": "Coimbra", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-526", "name": "Funchal", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-527", "name": "Amadora", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-528", "name": "Almada", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-529", "name": "Agualva-Cacém", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-530", "name": "Queluz", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-531", "name": "Guimarães", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-532", "name": "Odivelas", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-533", "name": "Matosinhos", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-534", "name": "Évora", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-535", "name": "Rio Tinto", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-536", "name": "Aveiro", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-537", "name": "Gondomar", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-538", "name": "Póvoa de Varzim", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-539", "name": "Corroios", "country": "Portekiz", "countryCode": "PT"},
    {"id": "PT-540", "name": "Esposende", "country": "Portekiz", "countryCode": "PT"},

    # Yunanistan (GR) - 20 major cities
    {"id": "GR-541", "name": "Atina", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-542", "name": "Selanik", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-543", "name": "Patras", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-544", "name": "İraklio", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-545", "name": "Larissa", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-546", "name": "Volos", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-547", "name": "Rodhos", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-548", "name": "İoannina", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-549", "name": "Chania", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-550", "name": "Chalcis", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-551", "name": "Agrinio", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-552", "name": "Katerini", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-553", "name": "Kalamata", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-554", "name": "Kavala", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-555", "name": "Kozani", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-556", "name": "Serres", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-557", "name": "Veria", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-558", "name": "Alexandroupoli", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-559", "name": "Drama", "country": "Yunanistan", "countryCode": "GR"},
    {"id": "GR-560", "name": "Tripoli", "country": "Yunanistan", "countryCode": "GR"},

    # İrlanda (IE) - 20 major cities
    {"id": "IE-561", "name": "Dublin", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-562", "name": "Cork", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-563", "name": "Limerick", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-564", "name": "Galway", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-565", "name": "Waterford", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-566", "name": "Drogheda", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-567", "name": "Dundalk", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-568", "name": "Swords", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-569", "name": "Bray", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-570", "name": "Navan", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-571", "name": "Ennis", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-572", "name": "Tralee", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-573", "name": "Carlow", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-574", "name": "Newbridge", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-575", "name": "Naas", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-576", "name": "Kilkenny", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-577", "name": "Sligo", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-578", "name": "Clonmel", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-579", "name": "Wexford", "country": "İrlanda", "countryCode": "IE"},
    {"id": "IE-580", "name": "Mullingar", "country": "İrlanda", "countryCode": "IE"},

    # Yeni Zelanda (NZ) - 20 major cities
    {"id": "NZ-581", "name": "Auckland", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-582", "name": "Wellington", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-583", "name": "Christchurch", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-584", "name": "Hamilton", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-585", "name": "Tauranga", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-586", "name": "Napier-Hastings", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-587", "name": "Dunedin", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-588", "name": "Palmerston North", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-589", "name": "Nelson", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-590", "name": "Rotorua", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-591", "name": "New Plymouth", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-592", "name": "Whangarei", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-593", "name": "Invercargill", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-594", "name": "Whanganui", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-595", "name": "Gisborne", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-596", "name": "Timaru", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-597", "name": "Masterton", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-598", "name": "Levin", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-599", "name": "Taupo", "country": "Yeni Zelanda", "countryCode": "NZ"},
    {"id": "NZ-600", "name": "Blenheim", "country": "Yeni Zelanda", "countryCode": "NZ"},

    # Singapur (SG) - 20 major cities
    {"id": "SG-601", "name": "Singapur", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-602", "name": "Jurong", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-603", "name": "Woodlands", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-604", "name": "Tampines", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-605", "name": "Bedok", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-606", "name": "Yishun", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-607", "name": "Hougang", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-608", "name": "Ang Mo Kio", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-609", "name": "Choa Chu Kang", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-610", "name": "Sembawang", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-611", "name": "Punggol", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-612", "name": "Sengkang", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-613", "name": "Bukit Batok", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-614", "name": "Pasir Ris", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-615", "name": "Bukit Panjang", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-616", "name": "Clementi", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-617", "name": "Queenstown", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-618", "name": "Toa Payoh", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-619", "name": "Kallang", "country": "Singapur", "countryCode": "SG"},
    {"id": "SG-620", "name": "Bishan", "country": "Singapur", "countryCode": "SG"},

    # Birleşik Arap Emirlikleri (AE) - 20 major cities
    {"id": "AE-621", "name": "Dubai", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-622", "name": "Abu Dhabi", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-623", "name": "Sharjah", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-624", "name": "Al Ain", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-625", "name": "Ajman", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-626", "name": "Ras Al Khaimah", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-627", "name": "Fujairah", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-628", "name": "Umm Al Quwain", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-629", "name": "Khor Fakkan", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-630", "name": "Dibba Al-Fujairah", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-631", "name": "Dhaid", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-632", "name": "Jebel Ali", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-633", "name": "Ruwais", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-634", "name": "Liwa", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-635", "name": "Ghayathi", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-636", "name": "Madinat Zayed", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-637", "name": "Al Dhafra", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-638", "name": "Zayed City", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-639", "name": "Sweihan", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},
    {"id": "AE-640", "name": "Al Wathba", "country": "Birleşik Arap Emirlikleri", "countryCode": "AE"},

    # Arjantin (AR) - 20 major cities
    {"id": "AR-641", "name": "Buenos Aires", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-642", "name": "Córdoba", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-643", "name": "Rosario", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-644", "name": "Mendoza", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-645", "name": "La Plata", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-646", "name": "San Miguel de Tucumán", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-647", "name": "Mar del Plata", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-648", "name": "Salta", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-649", "name": "Santa Fe", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-650", "name": "San Juan", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-651", "name": "Resistencia", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-652", "name": "Neuquén", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-653", "name": "Santiago del Estero", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-654", "name": "Corrientes", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-655", "name": "Bahía Blanca", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-656", "name": "Posadas", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-657", "name": "Paraná", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-658", "name": "San Salvador de Jujuy", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-659", "name": "Formosa", "country": "Arjantin", "countryCode": "AR"},
    {"id": "AR-660", "name": "San Luis", "country": "Arjantin", "countryCode": "AR"},

    # Şili (CL) - 20 major cities
    {"id": "CL-661", "name": "Santiago", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-662", "name": "Valparaíso", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-663", "name": "Concepción", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-664", "name": "La Serena", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-665", "name": "Antofagasta", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-666", "name": "Temuco", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-667", "name": "Rancagua", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-668", "name": "Talca", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-669", "name": "Arica", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-670", "name": "Chillán", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-671", "name": "Iquique", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-672", "name": "Puerto Montt", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-673", "name": "Los Ángeles", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-674", "name": "Coquimbo", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-675", "name": "Osorno", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-676", "name": "Valdivia", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-677", "name": "Punta Arenas", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-678", "name": "Copiapó", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-679", "name": "Quillota", "country": "Şili", "countryCode": "CL"},
    {"id": "CL-680", "name": "Curicó", "country": "Şili", "countryCode": "CL"},

    # Kolombiya (CO) - 20 major cities
    {"id": "CO-681", "name": "Bogotá", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-682", "name": "Medellín", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-683", "name": "Cali", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-684", "name": "Barranquilla", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-685", "name": "Cartagena", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-686", "name": "Cúcuta", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-687", "name": "Bucaramanga", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-688", "name": "Pereira", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-689", "name": "Santa Marta", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-690", "name": "Ibagué", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-691", "name": "Pasto", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-692", "name": "Manizales", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-693", "name": "Neiva", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-694", "name": "Villavicencio", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-695", "name": "Armenia", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-696", "name": "Valledupar", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-697", "name": "Montería", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-698", "name": "Sincelejo", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-699", "name": "Popayán", "country": "Kolombiya", "countryCode": "CO"},
    {"id": "CO-700", "name": "Buenaventura", "country": "Kolombiya", "countryCode": "CO"},

]

COUNTRIES_AND_CITIES_SEED = {
    "countries": COUNTRIES_195,
    "cities": ALL_CITIES
}