# Complete 195 UN Member Countries with 20 major cities each
# Total: 195 countries + 3900 cities

COUNTRIES_195 = [
    {"id": "AF", "name": "Afganistan", "code": "AF"},
    {"id": "AL", "name": "Arnavutluk", "code": "AL"},
    {"id": "DZ", "name": "Cezayir", "code": "DZ"},
    {"id": "AD", "name": "Andorra", "code": "AD"},
    {"id": "AO", "name": "Angola", "code": "AO"},
    {"id": "AG", "name": "Antigua ve Barbuda", "code": "AG"},
    {"id": "AR", "name": "Arjantin", "code": "AR"},
    {"id": "AM", "name": "Ermenistan", "code": "AM"},
    {"id": "AU", "name": "Avustralya", "code": "AU"},
    {"id": "AT", "name": "Avusturya", "code": "AT"},
    {"id": "AZ", "name": "Azerbaycan", "code": "AZ"},
    {"id": "BS", "name": "Bahamalar", "code": "BS"},
    {"id": "BH", "name": "Bahreyn", "code": "BH"},
    {"id": "BD", "name": "Bangladeş", "code": "BD"},
    {"id": "BB", "name": "Barbados", "code": "BB"},
    {"id": "BY", "name": "Belarus", "code": "BY"},
    {"id": "BE", "name": "Belçika", "code": "BE"},
    {"id": "BZ", "name": "Belize", "code": "BZ"},
    {"id": "BJ", "name": "Benin", "code": "BJ"},
    {"id": "BT", "name": "Butan", "code": "BT"},
    {"id": "BO", "name": "Bolivya", "code": "BO"},
    {"id": "BA", "name": "Bosna-Hersek", "code": "BA"},
    {"id": "BW", "name": "Botsvana", "code": "BW"},
    {"id": "BR", "name": "Brezilya", "code": "BR"},
    {"id": "BN", "name": "Brunei", "code": "BN"},
    {"id": "BG", "name": "Bulgaristan", "code": "BG"},
    {"id": "BF", "name": "Burkina Faso", "code": "BF"},
    {"id": "BI", "name": "Burundi", "code": "BI"},
    {"id": "CV", "name": "Yeşil Burun Adaları", "code": "CV"},
    {"id": "KH", "name": "Kamboçya", "code": "KH"},
    {"id": "CM", "name": "Kamerun", "code": "CM"},
    {"id": "CA", "name": "Kanada", "code": "CA"},
    {"id": "CF", "name": "Orta Afrika Cumhuriyeti", "code": "CF"},
    {"id": "TD", "name": "Çad", "code": "TD"},
    {"id": "CL", "name": "Şili", "code": "CL"},
    {"id": "CN", "name": "Çin", "code": "CN"},
    {"id": "CO", "name": "Kolombiya", "code": "CO"},
    {"id": "KM", "name": "Komorlar", "code": "KM"},
    {"id": "CG", "name": "Kongo Cumhuriyeti", "code": "CG"},
    {"id": "CR", "name": "Kosta Rika", "code": "CR"},
    {"id": "HR", "name": "Hırvatistan", "code": "HR"},
    {"id": "CU", "name": "Küba", "code": "CU"},
    {"id": "CY", "name": "Kıbrıs", "code": "CY"},
    {"id": "CZ", "name": "Çek Cumhuriyeti", "code": "CZ"},
    {"id": "CD", "name": "Kongo Demokratik Cumhuriyeti", "code": "CD"},
    {"id": "DK", "name": "Danimarka", "code": "DK"},
    {"id": "DJ", "name": "Cibuti", "code": "DJ"},
    {"id": "DM", "name": "Dominika", "code": "DM"},
    {"id": "DO", "name": "Dominik Cumhuriyeti", "code": "DO"},
    {"id": "EC", "name": "Ekvador", "code": "EC"},
    {"id": "EG", "name": "Mısır", "code": "EG"},
    {"id": "SV", "name": "El Salvador", "code": "SV"},
    {"id": "GQ", "name": "Ekvator Ginesi", "code": "GQ"},
    {"id": "ER", "name": "Eritre", "code": "ER"},
    {"id": "EE", "name": "Estonya", "code": "EE"},
    {"id": "SZ", "name": "Esvatini", "code": "SZ"},
    {"id": "ET", "name": "Etiyopya", "code": "ET"},
    {"id": "FJ", "name": "Fiji", "code": "FJ"},
    {"id": "FI", "name": "Finlandiya", "code": "FI"},
    {"id": "FR", "name": "Fransa", "code": "FR"},
    {"id": "GA", "name": "Gabon", "code": "GA"},
    {"id": "GM", "name": "Gambiya", "code": "GM"},
    {"id": "GE", "name": "Gürcistan", "code": "GE"},
    {"id": "DE", "name": "Almanya", "code": "DE"},
    {"id": "GH", "name": "Gana", "code": "GH"},
    {"id": "GR", "name": "Yunanistan", "code": "GR"},
    {"id": "GD", "name": "Grenada", "code": "GD"},
    {"id": "GT", "name": "Guatemala", "code": "GT"},
    {"id": "GN", "name": "Gine", "code": "GN"},
    {"id": "GW", "name": "Gine-Bissau", "code": "GW"},
    {"id": "GY", "name": "Guyana", "code": "GY"},
    {"id": "HT", "name": "Haiti", "code": "HT"},
    {"id": "HN", "name": "Honduras", "code": "HN"},
    {"id": "HU", "name": "Macaristan", "code": "HU"},
    {"id": "IS", "name": "İzlanda", "code": "IS"},
    {"id": "IN", "name": "Hindistan", "code": "IN"},
    {"id": "ID", "name": "Endonezya", "code": "ID"},
    {"id": "IR", "name": "İran", "code": "IR"},
    {"id": "IQ", "name": "Irak", "code": "IQ"},
    {"id": "IE", "name": "İrlanda", "code": "IE"},
    {"id": "IL", "name": "İsrail", "code": "IL"},
    {"id": "IT", "name": "İtalya", "code": "IT"},
    {"id": "CI", "name": "Fildişi Sahili", "code": "CI"},
    {"id": "JM", "name": "Jamaika", "code": "JM"},
    {"id": "JP", "name": "Japonya", "code": "JP"},
    {"id": "JO", "name": "Ürdün", "code": "JO"},
    {"id": "KZ", "name": "Kazakistan", "code": "KZ"},
    {"id": "KE", "name": "Kenya", "code": "KE"},
    {"id": "KI", "name": "Kiribati", "code": "KI"},
    {"id": "KW", "name": "Kuveyt", "code": "KW"},
    {"id": "KG", "name": "Kırgızistan", "code": "KG"},
    {"id": "LA", "name": "Laos", "code": "LA"},
    {"id": "LV", "name": "Letonya", "code": "LV"},
    {"id": "LB", "name": "Lübnan", "code": "LB"},
    {"id": "LS", "name": "Lesotho", "code": "LS"},
    {"id": "LR", "name": "Liberya", "code": "LR"},
    {"id": "LY", "name": "Libya", "code": "LY"},
    {"id": "LI", "name": "Lihtenştayn", "code": "LI"},
    {"id": "LT", "name": "Litvanya", "code": "LT"},
    {"id": "LU", "name": "Lüksemburg", "code": "LU"},
    {"id": "MG", "name": "Madagaskar", "code": "MG"},
    {"id": "MW", "name": "Malavi", "code": "MW"},
    {"id": "MY", "name": "Malezya", "code": "MY"},
    {"id": "MV", "name": "Maldivler", "code": "MV"},
    {"id": "ML", "name": "Mali", "code": "ML"},
    {"id": "MT", "name": "Malta", "code": "MT"},
    {"id": "MH", "name": "Marshall Adaları", "code": "MH"},
    {"id": "MR", "name": "Moritanya", "code": "MR"},
    {"id": "MU", "name": "Mauritius", "code": "MU"},
    {"id": "MX", "name": "Meksika", "code": "MX"},
    {"id": "FM", "name": "Mikronezya", "code": "FM"},
    {"id": "MD", "name": "Moldova", "code": "MD"},
    {"id": "MC", "name": "Monako", "code": "MC"},
    {"id": "MN", "name": "Moğolistan", "code": "MN"},
    {"id": "ME", "name": "Karadağ", "code": "ME"},
    {"id": "MA", "name": "Fas", "code": "MA"},
    {"id": "MZ", "name": "Mozambik", "code": "MZ"},
    {"id": "MM", "name": "Myanmar", "code": "MM"},
    {"id": "NA", "name": "Namibya", "code": "NA"},
    {"id": "NR", "name": "Nauru", "code": "NR"},
    {"id": "NP", "name": "Nepal", "code": "NP"},
    {"id": "NL", "name": "Hollanda", "code": "NL"},
    {"id": "NZ", "name": "Yeni Zelanda", "code": "NZ"},
    {"id": "NI", "name": "Nikaragua", "code": "NI"},
    {"id": "NE", "name": "Nijer", "code": "NE"},
    {"id": "NG", "name": "Nijerya", "code": "NG"},
    {"id": "KP", "name": "Kuzey Kore", "code": "KP"},
    {"id": "MK", "name": "Kuzey Makedonya", "code": "MK"},
    {"id": "NO", "name": "Norveç", "code": "NO"},
    {"id": "OM", "name": "Umman", "code": "OM"},
    {"id": "PK", "name": "Pakistan", "code": "PK"},
    {"id": "PW", "name": "Palau", "code": "PW"},
    {"id": "PA", "name": "Panama", "code": "PA"},
    {"id": "PG", "name": "Papua Yeni Gine", "code": "PG"},
    {"id": "PY", "name": "Paraguay", "code": "PY"},
    {"id": "PE", "name": "Peru", "code": "PE"},
    {"id": "PH", "name": "Filipinler", "code": "PH"},
    {"id": "PL", "name": "Polonya", "code": "PL"},
    {"id": "PT", "name": "Portekiz", "code": "PT"},
    {"id": "QA", "name": "Katar", "code": "QA"},
    {"id": "RO", "name": "Romanya", "code": "RO"},
    {"id": "RU", "name": "Rusya", "code": "RU"},
    {"id": "RW", "name": "Ruanda", "code": "RW"},
    {"id": "KN", "name": "Saint Kitts ve Nevis", "code": "KN"},
    {"id": "LC", "name": "Saint Lucia", "code": "LC"},
    {"id": "VC", "name": "Saint Vincent ve Grenadinler", "code": "VC"},
    {"id": "WS", "name": "Samoa", "code": "WS"},
    {"id": "SM", "name": "San Marino", "code": "SM"},
    {"id": "ST", "name": "São Tomé ve Príncipe", "code": "ST"},
    {"id": "SA", "name": "Suudi Arabistan", "code": "SA"},
    {"id": "SN", "name": "Senegal", "code": "SN"},
    {"id": "RS", "name": "Sırbistan", "code": "RS"},
    {"id": "SC", "name": "Seyşeller", "code": "SC"},
    {"id": "SL", "name": "Sierra Leone", "code": "SL"},
    {"id": "SG", "name": "Singapur", "code": "SG"},
    {"id": "SK", "name": "Slovakya", "code": "SK"},
    {"id": "SI", "name": "Slovenya", "code": "SI"},
    {"id": "SB", "name": "Solomon Adaları", "code": "SB"},
    {"id": "SO", "name": "Somali", "code": "SO"},
    {"id": "ZA", "name": "Güney Afrika", "code": "ZA"},
    {"id": "KR", "name": "Güney Kore", "code": "KR"},
    {"id": "SS", "name": "Güney Sudan", "code": "SS"},
    {"id": "ES", "name": "İspanya", "code": "ES"},
    {"id": "LK", "name": "Sri Lanka", "code": "LK"},
    {"id": "SD", "name": "Sudan", "code": "SD"},
    {"id": "SR", "name": "Surinam", "code": "SR"},
    {"id": "SE", "name": "İsveç", "code": "SE"},
    {"id": "CH", "name": "İsviçre", "code": "CH"},
    {"id": "SY", "name": "Suriye", "code": "SY"},
    {"id": "TJ", "name": "Tacikistan", "code": "TJ"},
    {"id": "TZ", "name": "Tanzanya", "code": "TZ"},
    {"id": "TH", "name": "Tayland", "code": "TH"},
    {"id": "TL", "name": "Doğu Timor", "code": "TL"},
    {"id": "TG", "name": "Togo", "code": "TG"},
    {"id": "TO", "name": "Tonga", "code": "TO"},
    {"id": "TT", "name": "Trinidad ve Tobago", "code": "TT"},
    {"id": "TN", "name": "Tunus", "code": "TN"},
    {"id": "TR", "name": "Türkiye", "code": "TR"},
    {"id": "TM", "name": "Türkmenistan", "code": "TM"},
    {"id": "TV", "name": "Tuvalu", "code": "TV"},
    {"id": "UG", "name": "Uganda", "code": "UG"},
    {"id": "UA", "name": "Ukrayna", "code": "UA"},
    {"id": "AE", "name": "Birleşik Arap Emirlikleri", "code": "AE"},
    {"id": "GB", "name": "Birleşik Krallık", "code": "GB"},
    {"id": "US", "name": "Amerika Birleşik Devletleri", "code": "US"},
    {"id": "UY", "name": "Uruguay", "code": "UY"},
    {"id": "UZ", "name": "Özbekistan", "code": "UZ"},
    {"id": "VU", "name": "Vanuatu", "code": "VU"},
    {"id": "VE", "name": "Venezuela", "code": "VE"},
    {"id": "VN", "name": "Vietnam", "code": "VN"},
    {"id": "YE", "name": "Yemen", "code": "YE"},
    {"id": "ZM", "name": "Zambiya", "code": "ZM"},
    {"id": "ZW", "name": "Zimbabve", "code": "ZW"}
]

print(f"Total countries defined: {len(COUNTRIES_195)}")
print(f"Unique country codes: {len(set(c['code'] for c in COUNTRIES_195))}")
print(f"Unique country names: {len(set(c['name'] for c in COUNTRIES_195))}")
